### ISSUE TITLE
Desacoplar Service com camada Web

### ISSUE THREAD

**Issue by iagosaito** [doniztjnr/beskar#4]
Todos esses métodos da classe de Service estão muito acoplados com classes que deveriam estar no Controller. Por exemplo, o método de delete: 

```
    // DELETE BY ID
    ResponseEntity<?> deleteOneFilmById(Long id) {
        repository.deleteById(id);

        return ResponseEntity.noContent().build();
    }
```

Está retornando um **ResponseEntity<?>**, essa classe de ResponseEntity é responsável por encapsular uma resposta HTTP. Será que o Service que é responsável pela camada de lógica de negócio devem ter classes que possuem conhecimento de status HTTP- como o NoContent que responde 204, por exemplo? 

O mais correto seria que a classe de Service retornasse apenas a entidade Film ou não retornasse nada. Qualquer coisa relacionado a HTTP ou RepresentationModel deveria estar na camada de Controller

**Comment by doniztjnr** [comment]
### Modificações feitas
O **service** da aplicação agora está responsável apenas em se comunicar com o **repository** para fazer as devidas modificações dos dados.
E o **controller** está responsável por retornar o **http response**.
```
    void deleteOneFilmById(Long id) {
        repository.deleteById(id);
    }
```
```
    @DeleteMapping(path = "/films/{id}")
    ResponseEntity<?> deleteFilm(@PathVariable Long id) {
        service.deleteOneFilmById(id);

        return ResponseEntity.noContent().build();
    }
```
As devidas modificações foram aplicadas a todos os métodos da classe **controller** e **service**.
:grin:
Obrigado !!!
