### ISSUE TITLE
Utilizar DTO´s

### ISSUE THREAD

**Issue by iagosaito** [doniztjnr/beskar#5]
A solução com DTO´s ainda está errada. O que você fez foi inserir um HATEOAS no projeto, que é algo muito mais complexo, por sinal. 

Criar DTO´s e utilizá-los no projeto é bem mais simples, sugiro que dê uma olhada neste artigo: https://marioalvial.medium.com/blindando-sua-api-spring-boot-com-o-padr%C3%A3o-dto-44f97020d1a0

**Comment by doniztjnr** [comment]
DTO implementado no projeto.
```
FilmDTO displayOneFilmById(Long id) {
        Film film = repository.findById(id)
                .orElseThrow(() -> new FilmNotFoundException(id));
        return new FilmDTO(film);
}
```
Usando ModelMapper.
````
List<FilmDTO> displayAllFilms() {
        List<Film> films = repository.findAll();
        ModelMapper modelMapper = new ModelMapper();
        return films.stream()
                .map(film -> modelMapper.map(film, FilmDTO.class))
                .toList();
}

**Comment by doniztjnr** [comment]
Obrigado
😃
